language: swift

env:
  global:
    - PROJECT="Codable.xcodeproj"
    - IOS_SCHEME="Codable-iOS"
    - MACOS_SCHEME="Codable-macOS"
    - TVOS_SCHEME="Codable-tvOS"
    - WATCHOS_SCHEME="Codable-watchOS"

matrix:
  include:

    - osx_image: xcode8.3
      env: POD_LINT="YES" RUN_TESTS="NO"

    - osx_image: xcode8.3
      env: DESTINATION="OS=9.0,name=iPhone 5" SDK="iphonesimulator10.3" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" POD_LINT="NO"

    - osx_image: xcode8.3
      env: DESTINATION="OS=10.3,name=iPhone 7" SDK="iphonesimulator10.3" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" POD_LINT="NO"

    - osx_image: xcode8.3
      env: DESTINATION="arch=x86_64" SDK="macosx10.12" SCHEME="$MACOS_SCHEME" RUN_TESTS="YES" POD_LINT="NO"
    
    - osx_image: xcode8.3
      env: DESTINATION="OS=10.0,name=Apple TV 1080p" SDK="appletvsimulator10.2" SCHEME="$TVOS_SCHEME" RUN_TESTS="YES" POD_LINT="NO"
    
    - osx_image: xcode8.3
      env: DESTINATION="OS=3.2,name=Apple Watch Series 2 - 42mm" SDK="watchsimulator3.2" SCHEME="$WATCHOS_SCHEME" RUN_TESTS="YES" POD_LINT="NO"

    - osx_image: xcode9.3beta
      env: POD_LINT="YES" RUN_TESTS="NO"

    - osx_image: xcode9.3beta
      env: DESTINATION="OS=9.0,name=iPhone 5" SDK="iphonesimulator11.3" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" POD_LINT="NO"

    - osx_image: xcode9.3beta
      env: DESTINATION="OS=10.3,name=iPhone 7" SDK="iphonesimulator11.3" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" POD_LINT="NO"

    - osx_image: xcode9.3beta
      env: DESTINATION="OS=11.3,name=iPhone X" SDK="iphonesimulator11.3" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" POD_LINT="NO"

    - osx_image: xcode9.3beta
      env: DESTINATION="arch=x86_64" SDK="macosx10.13" SCHEME="$MACOS_SCHEME" RUN_TESTS="YES" POD_LINT="NO"
    
    - osx_image: xcode9.3beta
      env: DESTINATION="OS=11.2,name=Apple TV 1080p" SDK="appletvsimulator11.2" SCHEME="$TVOS_SCHEME" RUN_TESTS="YES" POD_LINT="NO"
    
    - osx_image: xcode9.3beta
      env: DESTINATION="OS=4.3,name=Apple Watch Series 3 - 42mm" SDK="watchsimulator4.3" SCHEME="$WATCHOS_SCHEME" RUN_TESTS="YES" POD_LINT="NO"

script:
- set -o pipefail

- if [ $POD_LINT == "YES" ]; then
      gem update cocoapods;
      pod lib lint;
  fi

- if [ $RUN_TESTS == "YES" ]; then
      xcodebuild analyze test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
  else
      xcodebuild build analyze -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
  fi